Develop
cvilla714/bootstrap pull request #1
Opened 2020-09-24 22:44 UTC by cvilla714

2020-09-25 01:27 UTC, jubaan requested changes
# Status: INVALID

## :wave: :wave: Hi there Team!!

Before submitting a project, ensure the project is ready to be reviewed.

- [ ] This is how the site looks from the live link preview and the files uploaded. (see image below)

- [ ] Create a [Professional README File](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) The actual one is not descriptive enough.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

![image](https://user-images.githubusercontent.com/25774518/94216158-50170900-fea4-11ea-8752-3b11a1d90558.png)

2020-09-25 17:36 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've really done an amazing job so far, most especially with the responsiveness :ok:. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

_As the main point of this project is to use Bootstrap, I will focus on this in my review. You're asked to be more precise and to make sure that your page looks exactly the same as the source page.__

- [ ] Naming your pull request `Develop` is not meaningful enough. Please try to use a meaningful pull request title.

- [x] Since you're expected to be more precise with this project, try to use the same colors and boldings (buttons, headings etc) as used in the original page.

- [x] You're expected to use bootstrap **everywhere**. Most of the rules in your CSS file can be achieved with some CSS classes. Please check out boostrap typography classes and use more of them.

![18:32:58](https://user-images.githubusercontent.com/26856491/94298174-8d8b9d00-ff5d-11ea-9f45-bd695f5afcef.png)

- [x] Always adhere to the CSS good practices.
- You have a lot of repetitions in your CSS rules. Check the ones I commented on below and make necessary corrections.
- You overused the `!important` rule. There are better ways of implementing that feature. Refactor your code to avoid overusing of the rule.
- [Check this article] for a better understanding of CSS good practices.

- [x] The hambugger icon is missing on the navigation bar for small and medium screen sizes.

Source page: 
![18:04:06](https://user-images.githubusercontent.com/26856491/94295689-882c5380-ff59-11ea-864e-05f2c5707f01.png)

Your page: 
![18:02:01](https://user-images.githubusercontent.com/26856491/94295529-469ba880-ff59-11ea-9c61-279bf25105da.png)

- [x] In the `OPINION` section, the title of the opinions and the authors are in bold format. Observe the different from the image below and make necessary adjustments.

Source page: 
![18:07:08](https://user-images.githubusercontent.com/26856491/94296085-2f10ef80-ff5a-11ea-9c74-543d5c54ff38.png)

Your page: 
![18:07:36](https://user-images.githubusercontent.com/26856491/94296121-3afcb180-ff5a-11ea-827c-536e3a5527eb.png)

- [x] Observe the color and boldness of your headings in the slideshow section (US, WORLD, BUSINESS, etc) and the horizontal line. The line comes before the headings, not after them as you have in your page.

Source page:
![18:13:19](https://user-images.githubusercontent.com/26856491/94296644-12c18280-ff5b-11ea-99cd-8d5eff66bbe0.png)

Your page:
![18:14:03](https://user-images.githubusercontent.com/26856491/94296660-19e89080-ff5b-11ea-86e1-262af688cdeb.png)

- [ ] Check your subscribe and newsletter sections in both small and medium screen sizes. See the image below and observe the difference.

Source page:
![18:18:12](https://user-images.githubusercontent.com/26856491/94302447-21606780-ff64-11ea-8c5f-70d80933fb2d.png)

**On medium screens**
Your page: 
![18:19:15](https://user-images.githubusercontent.com/26856491/94297089-d7738380-ff5b-11ea-9499-d229f0dd3b2d.png)

**On large screens**
Source page:
![18:24:39](https://user-images.githubusercontent.com/26856491/94297453-6ed8d680-ff5c-11ea-87e0-99e8e14c7e63.png)
402
Your page:
![18:23:01](https://user-images.githubusercontent.com/26856491/94297465-74ceb780-ff5c-11ea-9510-dfb3baac7fbc.png)

- [ ] On large and medium screens, you are having some unnecessary space after the footer section of your page.

Source page:
![18:26:42](https://user-images.githubusercontent.com/26856491/94297640-bcedda00-ff5c-11ea-9d1e-ba6b66fc76ed.png)

Your page:
![18:25:54](https://user-images.githubusercontent.com/26856491/94297655-c119f780-ff5c-11ea-8a12-839e40634325.png)

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-09-25 17:36 UTC, teekaytech commented on css/style.css
> +}
You should stick to using class names for your CSS selectors. Using ID is not a good CSS practice. Kindly change the selector to class.

2020-09-25 17:36 UTC, teekaytech commented on css/style.css
> +}
Always keep your code DRY. You have a lot of duplicate rules in the blocks above. Rules like `font-size, line-height, cursor, etc` in the above blocks should be grouped. Please group common rules to avoid repetition.

2020-09-25 17:36 UTC, teekaytech commented on css/style.css
> +}
Apply the DRY rule to these blocks and other places where you have repetition of rules.

2020-09-25 17:36 UTC, teekaytech commented on css/style.css
> +  line-height: 16px !important;
The `!important` rule is great, but you're advised against it. When overused, it can quickly mess up your stylings. Please find a way to make things work without this rule.

2020-09-25 17:36 UTC, teekaytech commented on index.html
> +        <img class="nw-main-logo" src="./images/Newsweek_main_logo.PNG" alt="" />
Please give the `alt` attribute value for this image.

2020-09-25 17:36 UTC, teekaytech commented on index.html
> +              <img src="./images/arthur-lieber.png" class="mr-3" alt="..." />
Always give the value of the image tag's `alt` attribute

2020-09-25 17:36 UTC, teekaytech commented on index.html
> +              <img src="./images/john-dale-grover.png" class="mr-3" alt="..." />
Using ... does not have any semantic meaning. Use words that describe the images when they are not rendered.

2020-09-26 01:43 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-26 02:00 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Update the README file as privious TSE described
- [ ] Remove inline-styling and `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)



### Navbar
- [ ] On 768px there is no user icon in navbar, there is a **Login**. Please fix this issue

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://cvilla714.github.io/bootstrap/#)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94327490-d1fe5380-ffc4-11ea-83aa-d595352d3b77.png)|![clone](https://user-images.githubusercontent.com/29689273/94327499-e17d9c80-ffc4-11ea-9ac7-8cfd5f65c8a5.png)|

### Footer
- [ ] remove the extra padding

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://cvilla714.github.io/bootstrap/#)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94327516-fa864d80-ffc4-11ea-8d59-62e28daf42ed.png)|![clone](https://user-images.githubusercontent.com/29689273/94327524-07a33c80-ffc5-11ea-8444-d1798fe2664c.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-26 02:00 UTC, umairarshadbutt commented on css/style.css
> +    display: flex !important;
Remove  `!important`

2020-09-26 02:00 UTC, umairarshadbutt commented on index.html
> +            <div class="card mb-3 sub_subscripe subcolor" style="max-width: 100%">
remove inline-style

2020-09-26 02:00 UTC, umairarshadbutt commented on index.html
> +            <div class="card mb-3 sub_subscripe subcolor mb-md-4" style="max-width: 100%">
Remove inline-style

2020-09-26 03:02 UTC, cvilla714 commented on css/style.css
> +    display: flex !important;
I cannot remove important from this particular media query because otherwise, the code won't work as expected

2020-09-26 03:03 UTC, cvilla714 commented on index.html
> +            <div class="card mb-3 sub_subscripe subcolor" style="max-width: 100%">
ok done

2020-09-26 03:03 UTC, cvilla714 commented on index.html
> +            <div class="card mb-3 sub_subscripe subcolor mb-md-4" style="max-width: 100%">
done

2020-09-26 03:09 UTC, cvilla714 commented on css/style.css
> +    display: flex !important;
the important rule I was overusing it so as a requested change  of the previous code reviewer  I got rid of almost all of it, as you can see I was using it several times, now I only have used it once

2020-09-26 07:41 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hi, @cvilla714 and @Huemac-Alfredo. 
Both of you have done well on this project. Let's make a few changes, and we will be done.
You might have broken a few codes while fixing the extra padding requested by the previous TSE

- [x] The newsletter image is missing at a breakpoint of 767px down. Please see the image below: 
![newsletter](https://user-images.githubusercontent.com/5264771/94332542-15a98b00-ffce-11ea-86d7-872846d52893.jpg)

- [x] Remove the border-right from the footer menu as is removed from the original at a breakpoint of 768px down. Refer to the screenshot below:
![newsweek_footer_pa](https://user-images.githubusercontent.com/5264771/94332649-cc0d7000-ffce-11ea-9760-4704862f1cd2.jpg)

- [x] We have to make sure nothing is messed up, see the image below, fix the border-right line on the large screen as seen on the original. 
![newsweek-footer-border](https://user-images.githubusercontent.com/5264771/94334970-f01d8100-ffcf-11ea-8633-bea2d9494400.jpg)

- [ ] There's a lot of images that need to be made 100% as you transition to the 767px breakpoint, see the image illustration. The clone is the one on the right. 

![newsweek_extra-space](https://user-images.githubusercontent.com/5264771/94335415-6d96c080-ffd3-11ea-8837-7ab88e241c35.gif)

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-09-27 00:01 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

#### Hi, @cvilla714  and @Huemac-Alfredo  
**Congratulations**  🎉 🎉 🎉  on completing your project, and taking the time to implement the changes requested by the TSEs.  I really commend your effort in putting in such a great deal of work to complete this project. It will sure look good on your profile.

Feel free to merge when ready. I wish you all the best in your next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-09-27 18:02 UTC, merged